### ISSUE TITLE
Update Haskell Platform?

### ISSUE THREAD

**Issue by seanhess** [instructure/straitjacket#3]
Hi there, 

I'm hoping to use haskell for the competition next week, but your version is a few years old (ghc 7.6 is from 2013). 

I would be happy to create a pull request to your dockerfile fixing this, but I want to make sure my time isn't wasted. Would you accept one? I can mimic the approach you are taking so far, but is there anything to keep in mind?

**Comment by codekitchen** [comment]
Sure. Ideally you'd stick with the same `buildpack-deps:jessie` base image, other than that I think it'd be straightforward.

**Comment by seanhess** [comment]
I added a PR here: https://github.com/instructure/straitjacket/pull/4

**Comment by seanhess** [comment]
Closing this since you merged. Please check out my other PR https://github.com/instructure/straitjacket/pull/5 for an optimization flag. Thanks!
